export const AJAX_CALL_BEGIN = 'AJAX_CALL_BEGIN';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';

export const LOG_IN = 'LOG_IN';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';

export const LOG_OUT = 'LOG_OUT';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const PUBLISH_OFFICE = 'PUBLISH_OFFICE';
export const PUBLISH_OFFICE_LOADING = 'PUBLISH_OFFICE_LOADING';
export const PUBLISH_OFFICE_SUCCESS = 'PUBLISH_OFFICE_SUCCESS';

export const SEARCH_OFFICE = 'SEARCH_OFFICE';
export const SEARCH_OFFICE_SUCCESS = 'SEARCH_OFFICE_SUCCESS';

export const SEARCH_DOCTOR = 'SEARCH_DOCTOR';
export const SEARCH_DOCTOR_SUCCESS = 'SEARCH_DOCTOR_SUCCESS';

export const LOAD_METADATA = 'LOAD_METADATA';
export const LOAD_METADATA_SUCCESS = 'LOAD_METADATA_SUCCESS';

export const UPDATE_METADATA = 'UPDATE_METADATA';
export const UPDATE_METADATA_SUCCESS = 'UPDATE_METADATA_SUCCESS';

export const LOAD_OFFICE_DATA = 'LOAD_OFFICE_DATA';
export const LOAD_OFFICE_DATA_SUCCESS = 'LOAD_OFFICE_DATA_SUCCESS';

export const LOAD_DENTAL_TEAM = 'LOAD_DENTAL_TEAM';
export const LOAD_DENTAL_TEAM_SUCCESS = 'LOAD_DENTAL_TEAM_SUCCESS';

export const ADD_DENTAL_TEAM_MEMBER = 'ADD_DENTAL_TEAM_MEMBER';
export const ADD_DENTAL_TEAM_MEMBER_SUCCESS = 'ADD_DENTAL_TEAM_MEMBER_SUCCESS';

export const DELETE_DENTAL_TEAM_MEMBER = 'DELETE_DENTAL_TEAM_MEMBER';
export const DELETE_DENTAL_TEAM_MEMBER_SUCCESS = 'DELETE_DENTAL_TEAM_MEMBER_SUCCESS';

export const LOAD_SERVICES = 'LOAD_SERVICES';
export const LOAD_SERVICES_SUCCESS = 'LOAD_SERVICES_SUCCESS';

export const UPDATE_SERVICES = 'UPDATE_SERVICES';
export const UPDATE_SERVICES_SUCCESS = 'UPDATE_SERVICES_SUCCESS';

export const DELETE_SERVICES = 'DELETE_SERVICES';
export const DELETE_SERVICES_SUCCESS = 'DELETE_SERVICES_SUCCESS';

export const LOAD_FEATURED_SERVICES = 'LOAD_FEATURED_SERVICES';
export const LOAD_FEATURED_SERVICES_SUCCESS = 'LOAD_FEATURED_SERVICES_SUCCESS';

export const UPDATE_FEATURED_SERVICES = 'UPDATE_FEATURED_SERVICES';
export const UPDATE_FEATURED_SERVICES_SUCCESS = 'UPDATE_FEATURED_SERVICES_SUCCESS';

export const CLOUDINARY_UPLOAD_SINGLE_IMAGE = 'CLOUDINARY_UPLOAD_SINGLE_IMAGE';
export const CLOUDINARY_LOAD_IMAGE_LIST = 'CLOUDINARY_LOAD_IMAGE_LIST';
export const CLOUDINARY_LOAD_IMAGE_LIST_SUCCESS = 'CLOUDINARY_LOAD_IMAGE_LIST_SUCCESS';

export const LOAD_PROMOTIONS = 'LOAD_PROMOTIONS';
export const LOAD_PROMOTIONS_SUCCESS = 'LOAD_PROMOTIONS_SUCCESS';

export const SAVE_PROMOTION = 'SAVE_PROMOTION';
export const SAVE_PROMOTION_SUCCESS = 'SAVE_PROMOTION_SUCCESS';

export const LOAD_DENTAL_TEAM_BIO = 'LOAD_DENTAL_TEAM_BIO';
export const LOAD_DENTAL_TEAM_BIO_SUCCESS = 'LOAD_DENTAL_TEAM_BIO_SUCCESS';

export const UPDATE_DENTAL_TEAM_MEMBER_BIO = 'UPDATE_DENTAL_TEAM_MEMBER_BIO';
export const UPDATE_DENTAL_TEAM_MEMBER_BIO_SUCCESS = 'UPDATE_DENTAL_TEAM_MEMBER_BIO_SUCCESS';

export const UPDATE_SINGLE_DENTAL_TEAM_MEMBER_BIO = 'UPDATE_SINGLE_DENTAL_TEAM_MEMBER_BIO';
export const UPDATE_SINGLE_DENTAL_TEAM_MEMBER_BIO_SUCCESS = 'UPDATE_SINGLE_DENTAL_TEAM_MEMBER_BIO_SUCCESS';
export const LOAD_CUSTOMIZE_HOME_DATA = 'LOAD_CUSTOMIZE_HOME_DATA';
export const LOAD_CUSTOMIZE_HOME_DATA_SUCCESS = 'LOAD_CUSTOMIZE_HOME_DATA_SUCCESS';

export const UPDATE_CUSTOMIZE_HOME_DATA = 'UPDATE_CUSTOMIZE_HOME_DATA';
export const UPDATE_CUSTOMIZE_HOME_DATA_SUCCESS = 'UPDATE_CUSTOMIZE_HOME_DATA_SUCCESS';

export const LOAD_HOME_WIDGETS = 'LOAD_HOME_WIDGETS';
export const LOAD_HOME_WIDGETS_SUCCESS = 'LOAD_HOME_WIDGETS_SUCCESS';

export const UPDATE_HOME_WIDGETS = 'UPDATE_HOME_WIDGETS';
export const UPDATE_HOME_WIDGETS_SUCCESS = 'UPDATE_HOME_WIDGETS_SUCCESS';

export const CLOUDINARY_UPLOAD_IMAGES = 'CLOUDINARY_UPLOAD_IMAGES';
export const CLOUDINARY_UPLOAD_IMAGES_SUCCESS = 'CLOUDINARY_UPLOAD_IMAGES_SUCCESS';

export const SEND_TELEMETRY_ERROR = 'SEND_TELEMETRY_ERROR';
export const SEND_TELEMETRY_ERROR_SUCCESS = 'SEND_TELEMETRY_ERROR_SUCCESS';


export const LOAD_DOCTORS = 'LOAD_DOCTORS';
export const LOAD_DOCTORS_SUCCESS = 'LOAD_DOCTORS_SUCCESS';

export const ADD_DOCTORS = 'ADD_DOCTORS';
export const ADD_DOCTORS_SUCCESS = 'ADD_DOCTORS_SUCCESS';

export const DELETE_DOCTORS = 'DELETE_DOCTORS';
export const DELETE_DOCTORS_SUCCESS = 'DELETE_DOCTORS_SUCCESS';

export const ARRANGE_DOCTORS = 'ARRANGE_DOCTORS';
export const ARRANGE_DOCTORS_SUCCESS = 'ARRANGE_DOCTORS_SUCCESS';

export const LOAD_DOCTOR_BIO = 'LOAD_DOCTOR_BIO';
export const LOAD_DOCTOR_BIO_SUCCESS = 'LOAD_DOCTOR_BIO_SUCCESS';
export const UPDATE_DOCTOR_BIO = 'UPDATE_DOCTOR_BIO';
export const UPDATE_DOCTOR_BIO_SUCCESS = 'UPDATE_DOCTOR_BIO_SUCCESS';

export const LOAD_DENTIST_CHAIR = 'LOAD_DENTIST_CHAIR';
export const LOAD_DENTIST_CHAIR_SUCCESS = 'LOAD_DENTIST_CHAIR_SUCCESS';
export const LOAD_DENTIST_CHAIR_DOCTORS_SUCCESS = 'LOAD_DENTIST_CHAIR_DOCTORS_SUCCESS';

export const UPDATE_DENTIST_CHAIR_DOCTORS = 'UPDATE_DENTIST_CHAIR_DOCTORS';
export const UPDATE_DENTIST_CHAIR_DOCTORS_SUCCESS = 'UPDATE_DENTIST_CHAIR_DOCTORS_SUCCESS';